# Site settings
title: Connor Makes Games
email: connor@huckaby.dev
description: Connor's online e-porfolio for video game development.
baseurl: ""
url: "https://www.floofs.dev"
twitter_username: floofsdev
github_username:  floofs

# Build settings
sass:
sass_dir: _sass
include: ['_pages']
kramdown:
input: GFM