# Site settings
title: Floofs' GameDev Portfolio
email: connor@huckaby.dev
description: Floofs' website for his game development projects.
baseurl: ""
url: "https://www.floofs.dev"
twitter_username: floofsdev
github_username:  floofs

# Build settings
sass:
sass_dir: _sass
include: ['_pages']
kramdown:
input: GFM